### ISSUE TITLE
ubuntu系统运行，出现错误

### ISSUE THREAD

**Issue by kevinmy35** [shaodahong/jd-happy#4]
正在初始化浏览器……
   初始化完成，开始抓取页面
(node:4243) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): AssertionError [ERR_ASSERTION]: ERROR: "networkidle" option is no longer supported. Use "networkidle2" instead
(node:4243) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

卡在这个动不了，顺便问一下哪个地区信息怎么看啊？教程中的那个文件怎么调出来。谢谢

**Comment by shaodahong** [comment]
检查，也就是开发者工具，windows 是 f12 好像，mac 是 command + option + j，ubuntu 我没有测试过，建议删除下 node_modules，然后重新 install 下

**Comment by kevinmy35** [comment]
我这用的chrome，按下f12，得到的截图。具体在哪看啊，大神求指导，谢谢。
![2017-11-16 12-51-09](https://user-images.githubusercontent.com/22651095/32874479-7596d380-cacd-11e7-9c04-618c7763a975.png)

**Comment by shaodahong** [comment]
@kevinmy35 network

**Comment by kevinmy35** [comment]
大神，我重新卸载之后，又安装，还是报同样的错.这该怎么办？谢谢

**Comment by shaodahong** [comment]
重新拉下代码试试，已更新
